export enum ELang {
  // bg = 'bg',
  // cs = 'cs',
  da = 'da',
  de = 'de',
  // el = 'el',
  en = 'en',
  es = 'es',
  // et = 'et',
  // fi = 'fi',
  fr = 'fr',
  // ga = 'ga',
  // hr = 'hr',
  // hu = 'hu',
  it = 'it',
  // lt = 'lt',
  // lv = 'lv',
  // mt = 'mt',
  nl = 'nl',
  // pl = 'pl',
  pt = 'pt',
  // ro = 'ro',
  // sk = 'sk',
  // sl = 'sl',
  // sv = 'sv',
  uk = 'uk',
}
