export enum EMainTabs {
  Tasks = 'Tasks',
  Habits = 'Habits',
  Rewards = 'Rewards',
  More = 'More',
}

export enum EScreens {
  // MainTabs = 'MainTabs',
  Settings = 'more/Settings/Settings',
  LoadedPhotos = 'more/LoadedPhotos/LoadedPhotos',
  HelpCenter = 'more/HelpCenter/HelpCenter',
  Users = 'users/Users',
  UserAdd = 'users/UserAdd',
  UserEdit = 'users/UserEdit',
  UsersRemove = 'users/UsersRemove',
  ParentAdd = 'users/ParentAdd',
  ParentEdit = 'users/ParentEdit',
  ParentRemove = 'users/ParentRemove',
  ChildAdd = 'users/ChildAdd',
  ChildEdit = 'users/ChildEdit',
  ChildRemove = 'users/ChildRemove',
  DefaultTasks = 'tasks/DefaultTasks',
  BaseTasks = 'tasks/BaseTasks',
  BaseTaskAdd = 'tasks/BaseTaskAdd',
  BaseTaskEdit = 'tasks/BaseTaskEdit',
  Tasks = 'tasks/Tasks',
  TaskAssignmentAdd = 'tasks/TaskAssignmentAdd',
  TaskAssignmentEdit = 'tasks/TaskAssignmentEdit',
  FilteredTasks = 'tasks/FilteredTasks',
  BaseRewards = 'rewards/BaseRewards',
  BaseRewardAdd = 'rewards/BaseRewardAdd',
  BaseRewardEdit = 'rewards/BaseRewardEdit',
  RewardAdd = 'rewards/RewardAdd',
  RewardEdit = 'rewards/RewardEdit',
  WelcomeSteps = 'users/WelcomeSteps',
  Onboarding = '(onboarding)',
}
