export enum EMainTabs {
  Tasks = 'Tasks',
  Routines = 'Routines',
  Rewards = 'Rewards',
  More = 'More',
}

export enum EScreens {
  // MainTabs = 'MainTabs',
  Settings = 'more/Settings/Settings',
  Users = 'users/Users',
  UserAdd = 'users/UserAdd',
  UserEdit = 'users/UserEdit',
  UsersRemove = 'users/UsersRemove',
  ParentAdd = 'users/ParentAdd',
  ParentEdit = 'users/ParentEdit',
  ParentRemove = 'users/ParentRemove',
  ChildAdd = 'users/ChildAdd',
  ChildEdit = 'users/ChildEdit',
  ChildRemove = 'users/ChildRemove',
  DefaultTasks = 'tasks/DefaultTasks',
  BaseTasks = 'tasks/BaseTasks',
  BaseTaskAdd = 'tasks/BaseTaskAdd',
  BaseTaskEdit = 'tasks/BaseTaskEdit',
  BaseTaskRemove = 'tasks/BaseTaskRemove',
  TaskAdd = 'tasks/TaskAdd',
  TaskEdit = 'tasks/TaskEdit',
  TaskRemove = 'tasks/TaskRemove',
  WelcomeSteps = 'users/WelcomeSteps',
}
